import { MEASUREMENT_TYPE } from "@/src/constants/workout.constants";

export const WEIGHT_DISPLAY = "weight";
export const REPS_DISPLAY = "reps";
export const TIME_DISPLAY = "time";
export const DISTANCE_DISPLAY = "distance";

export const MEASUREMENT_TYPE_DISPLAYS = {
  [MEASUREMENT_TYPE.REPS_AND_ADDED_WEIGHT]: [WEIGHT_DISPLAY, REPS_DISPLAY],
  [MEASUREMENT_TYPE.REPS_AND_SUBTRACTED_WEIGHT]: [WEIGHT_DISPLAY, REPS_DISPLAY],
  [MEASUREMENT_TYPE.TIME_AND_ADDED_WEIGHT]: [WEIGHT_DISPLAY, TIME_DISPLAY],
  [MEASUREMENT_TYPE.REPS_ONLY]: [REPS_DISPLAY],
  [MEASUREMENT_TYPE.TIME_ONLY]: [TIME_DISPLAY],
  [MEASUREMENT_TYPE.TIME_AND_DISTANCE]: [TIME_DISPLAY, DISTANCE_DISPLAY],
};
